### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by SP642** [SP642/TheBan#1]
**FRONTEND:**
- [ ] 1. Choose layout and template
- [ ] 2. Choose style and color scheme
- [ ] 3. Define font and logo
(...)

**BACKEND:**
- [ ] 1. (...)
- [ ] 2. (...)
- [ ] 3. (...)
(...)

**BOTH:**
- [ ] 1. Define the editorial cut and working mechanism.
- [ ] 2. (...)
- [ ] 3. (...)
(...)
